"""M193b — log-sized (Bulletproofs-style) zero-knowledge argument for
the ridge-head relation y = <w, x> + b, with public weights w and a
committed input x.

Registered in ``RESEARCH_IMPLEMENTATION_PLAN_v25.md`` section 6
(19 Aug 2026, before the build). Protocol: the inner-product argument
with the fold equations from the dalek Bulletproofs notes —

    a' = a_lo*u + u^{-1}*a_hi
    b' = b_lo*u^{-1} + u*b_hi
    G' = G_lo^{u^{-1}} * G_hi^{u}
    H' = H_lo^{u} * H_hi^{u^{-1}}
    P' = P + u^2 * L + u^{-2} * R
    L = g^{rL} * <G_hi, a_lo> * <H_lo, b_hi> * Q^{<a_lo, b_hi>}
    R = g^{rR} * <G_lo, a_hi> * <H_hi, b_lo> * Q^{<a_hi, b_lo>}

with witness a = x (committed), public b = w. Group: a deterministic
seed-derived 256-bit safe prime — PROTOTYPE security parameter
(registered; production needs a standard curve/zk stack). Proof size
is O(log n) group elements.
"""
from __future__ import annotations

import hashlib
import random as _random
from typing import Any, Sequence

# ---------------------------------------------------------------- group setup
def _miller_rabin(n: int, rounds: int = 24) -> bool:
    if n < 4:
        return n in (2, 3)
    if n % 2 == 0:
        return False
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if a >= n:
            break
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


def _generate_safe_prime(bits: int = 256, seed: int = 20260823
                         ) -> tuple[int, int]:
    """Deterministic seed-derived safe prime p = 2q + 1 (prototype)."""
    rng = _random.Random(seed)
    while True:
        q = rng.getrandbits(bits - 1) | (1 << (bits - 2)) | 1
        if not _miller_rabin(q):
            continue
        p = 2 * q + 1
        if _miller_rabin(p):
            return p, q


P, Q_ORDER = _generate_safe_prime()


def _generator(index: int) -> int:
    digest = hashlib.sha256(f"geode-bp-{index}".encode("utf-8")).digest()
    h = int.from_bytes(digest, "big") % P
    h = pow(h, 2, P)
    if h == 1:
        h = 4
    return h


# Pedersen base with unknown discrete log, of prime order q. NOTE: the
# group element 2 has order 2q in this safe-prime group (2 is a
# quadratic non-residue), so every exponent must be taken in the
# order-q subgroup generated by BP_G — using base 2 anywhere makes the
# exponent arithmetic inconsistent (the unit gate caught exactly
# this). All hash generators are squares (QR), hence order-q too.
BP_G = _generator(-1)


def _challenge(*parts: bytes) -> int:
    state = hashlib.sha256()
    for part in parts:
        state.update(part)
    return int.from_bytes(state.digest(), "big") % Q_ORDER


def _ser(*values: int) -> bytes:
    return ";".join(format(int(v), "x") for v in values).encode("utf-8")


def _pad(vec: Sequence[int], n: int) -> list[int]:
    return [int(v) % Q_ORDER for v in vec] + [0] * (n - len(vec))


def _multiexp(pairs: Sequence[tuple[int, int]]) -> int:
    """prod base^exp mod P for (base, exp) pairs."""
    acc = 1
    for base, exp in pairs:
        acc = (acc * pow(int(base), int(exp) % Q_ORDER, P)) % P
    return acc


def commit_vec(x: Sequence[int], r: int, start: int) -> int:
    return _multiexp([(BP_G, int(r) % Q_ORDER)]
                     + [(_generator(start + i), int(xi))
                        for i, xi in enumerate(x)])


# ---------------------------------------------------------------- the argument
def prove(x: Sequence[int], r: int, w: Sequence[int],
          claim: int) -> dict[str, Any]:
    """Prove knowledge of x with C = Com(x; r) such that <w, x> = claim
    mod q. Deterministic for fixed (x, r, w, claim)."""
    size = 1
    while size < len(x):
        size *= 2
    n = size
    a = _pad(x, n)
    b = _pad(w, n)
    c_commit = commit_vec(x, r, 0)
    gens = [_generator(i) for i in range(n)]
    hgens = [_generator(n + i) for i in range(n)]
    q_gen = _generator(2 * n)

    rng = _random.Random(int(_challenge(_ser(int(r)))))
    ls, rs = [], []
    r_acc = int(r) % Q_ORDER
    m = n
    while m > 1:
        half = m // 2
        a_lo, a_hi = a[:half], a[half:]
        b_lo, b_hi = b[:half], b[half:]
        g_lo, g_hi = gens[:half], gens[half:]
        h_lo, h_hi = hgens[:half], hgens[half:]
        rl, rr = rng.randrange(Q_ORDER), rng.randrange(Q_ORDER)
        c_l = sum((ai * bi) % Q_ORDER for ai, bi in zip(a_lo, b_hi)) \
            % Q_ORDER
        c_r = sum((ai * bi) % Q_ORDER for ai, bi in zip(a_hi, b_lo)) \
            % Q_ORDER
        l_j = _multiexp([(BP_G, rl)] + [(g_hi[i], a_lo[i])
                                         for i in range(half)]
                        + [(h_lo[i], b_hi[i]) for i in range(half)]
                        + [(q_gen, c_l)])
        r_j = _multiexp([(BP_G, rr)] + [(g_lo[i], a_hi[i])
                                         for i in range(half)]
                        + [(h_hi[i], b_lo[i]) for i in range(half)]
                        + [(q_gen, c_r)])
        u = _challenge(_ser(l_j), _ser(r_j), _ser(c_commit))
        u_inv = pow(u, Q_ORDER - 2, Q_ORDER)
        u2 = (u * u) % Q_ORDER
        u2_inv = (u_inv * u_inv) % Q_ORDER
        a = [(a_lo[i] * u + a_hi[i] * u_inv) % Q_ORDER
             for i in range(half)]
        b = [(b_lo[i] * u_inv + b_hi[i] * u) % Q_ORDER
             for i in range(half)]
        gens = [(pow(g_lo[i], u_inv, P) * pow(g_hi[i], u, P)) % P
                for i in range(half)]
        hgens = [(pow(h_lo[i], u, P) * pow(h_hi[i], u_inv, P)) % P
                 for i in range(half)]
        r_acc = (r_acc + u2 * rl + u2_inv * rr) % Q_ORDER
        ls.append(l_j)
        rs.append(r_j)
        m = half
    return {"c_commit": c_commit, "L": ls, "R": rs,
            "a_final": int(a[0]) % Q_ORDER, "r_final": r_acc,
            "b_final": int(b[0]) % Q_ORDER, "claim": int(claim) % Q_ORDER}


def verify(proof: dict[str, Any], w: Sequence[int]) -> bool:
    """Verify against the committed input C and claimed <w, x>."""
    size = 1
    while size < len(w):
        size *= 2
    n = size
    b = _pad(w, n)
    gens = [_generator(i) for i in range(n)]
    hgens = [_generator(n + i) for i in range(n)]
    q_gen = _generator(2 * n)
    c_commit = int(proof["c_commit"]) % P
    claim = int(proof["claim"]) % Q_ORDER

    p_acc = (c_commit
             * _multiexp([(hgens[i], b[i]) for i in range(n)])
             * pow(q_gen, claim, P)) % P
    m = n
    for l_j, r_j in zip(proof["L"], proof["R"]):
        half = m // 2
        b_lo, b_hi = b[:half], b[half:]
        g_lo, g_hi = gens[:half], gens[half:]
        h_lo, h_hi = hgens[:half], hgens[half:]
        u = _challenge(_ser(l_j), _ser(r_j), _ser(c_commit))
        u_inv = pow(u, Q_ORDER - 2, Q_ORDER)
        u2 = (u * u) % Q_ORDER
        u2_inv = (u_inv * u_inv) % Q_ORDER
        b = [(b_lo[i] * u_inv + b_hi[i] * u) % Q_ORDER
             for i in range(half)]
        gens = [(pow(g_lo[i], u_inv, P) * pow(g_hi[i], u, P)) % P
                for i in range(half)]
        hgens = [(pow(h_lo[i], u, P) * pow(h_hi[i], u_inv, P)) % P
                 for i in range(half)]
        p_acc = (p_acc
                 * pow(l_j, u2, P) % P
                 * pow(r_j, u2_inv, P)) % P
        m = half
    a_final = int(proof["a_final"]) % Q_ORDER
    b_final = int(proof["b_final"]) % Q_ORDER
    if b_final != b[0]:
        return False
    rhs = (pow(BP_G, int(proof["r_final"]) % Q_ORDER, P)
           * pow(gens[0], a_final, P) % P
           * pow(hgens[0], b_final, P) % P
           * pow(q_gen, (a_final * b_final) % Q_ORDER, P)) % P
    return p_acc == rhs


def proof_size_bytes(proof: dict[str, Any]) -> int:
    """Each L/R is one 256-bit group element (32 bytes); two final
    scalars; the commitment; the claim."""
    rounds = len(proof["L"])
    return (rounds * 2 + 1) * 32 + 2 * 32 + 32
